engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true

exclude_paths:
  - "client/**/*"
  - "!client/assets/native/**/*"
  - "!client/test/selenium/**/*"